version: 0.2

env:
  variables:
    AWS_REGION:  'eu-west-2'
    BRANCH_NAME: '34_DAM-1032-IAPS-AWS-CodePipeline-AMI-Build'
    TARGET_ENV:  'dev'
    ARTIFACT_BUCKET: 'tf-eu-west-2-hmpps-eng-dev-config-s3bucket'
    ZAIZI_BUCKET: 'tf-eu-west-2-hmpps-eng-dev-artefacts-s3bucket'
    FILENAME:     'iaps-codebuild.json'
  parameter-store:
    WIN_ADMIN_PASS:  '/${TARGET_ENV}/jenkins/windows/slave/admin/password'
    GITHUB_ACCESS_TOKEN: "/jenkins/github/accesstoken"
phases:
  pre_build:
    commands:
      - echo "Installing Pre-Requisites"
      - ${CODEBUILD_SRC_DIR}/install-pre-reqs.sh
  build:
    commands:
      - echo $BRANCH_NAME
      - ${CODEBUILD_SRC_DIR}/packer-verify.sh 
      - ${CODEBUILD_SRC_DIR}/packer-build-windows.sh 
      