version: 0.2

env:
  variables:
    AWS_REGION:  'eu-west-2'
    BRANCH_NAME: '34_DAM-1032-IAPS-AWS-CodePipeline-AMI-Build'
    TARGET_ENV:  'dev'
    FILENAME:     'codebuild/iaps-codebuild.json'
  parameter-store:
    WIN_ADMIN_PASS:  '/dev/jenkins/windows/agent/admin/password'
    GITHUB_ACCESS_TOKEN: "/jenkins/github/accesstoken"
    ARTIFACT_BUCKET:     "/codebuild/artifact_bucket"
    ZAIZI_BUCKET:        "/codebuild/zaizi_bucket"
phases:
  pre_build:
    commands:
      - echo "Installing Pre-Requisites"
      - ${CODEBUILD_SRC_DIR}/codebuild/linux_vm/install-pre-reqs.sh
  build:
    commands:
      - echo $BRANCH_NAME
      - ${CODEBUILD_SRC_DIR}/codebuild/linux_vm/packer-verify.sh 
      - ${CODEBUILD_SRC_DIR}/codebuild/linux_vm/packer-build-windows.sh 
