version: 0.2

run-as: ubuntu

env:
  variables:
    AWS_REGION:  'eu-west-2'
    BRANCH_NAME: ${CODEBUILD_WEBHOOK_TRIGGER}
    TARGET_ENV:  'dev'
    ARTIFACT_BUCKET: 'tf-eu-west-2-hmpps-eng-dev-config-s3bucket'
    ZAIZI_BUCKET: 'tf-eu-west-2-hmpps-eng-dev-artefacts-s3bucket'
    FILENAME:     'iaps.json'
  parameter-store:
    WIN_ADMIN_PASS:  '/${TARGET_ENV}/jenkins/windows/slave/admin/password'
    GITHUB_ACCESS_TOKEN: "/jenkins/github/accesstoken"

phases:
  install:
    commands:
      - ${CODEBUILD_SRC_DIR}/install-pre-reqs.sh
  build:
    #run-as: Linux-user-name
    commands:
      - echo $BRANCH_NAME
      - ${CODEBUILD_SRC_DIR}/packer-verify.sh 
      - ${CODEBUILD_SRC_DIR}/packer-build-windows.sh 
#    finally:
#      - command
#  post_build:
#    run-as: Linux-user-name
#    commands:
#      - command
#    finally:
#      - command
   